//------------------------------------------------------------------------------
// <auto-generated>
//     Generated from the EDMX model (Database-First / EF6).
//     Manual changes may be overwritten if the model is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HubieTest.Dal
{
    public partial class APP_USER
    {
        public long USER_ID { get; set; }
        public string USER_NAME { get; set; }
        public string USER_LOGIN { get; set; }
        public string USER_PASSWORD { get; set; }
        public string USER_EMAIL { get; set; }
        public string USER_PROFILE { get; set; }
        public bool USER_ACTIVE { get; set; }
    }
}
