//------------------------------------------------------------------------------
// <auto-generated>
//     Generated from the EDMX model (Database-First / EF6).
// </auto-generated>
//------------------------------------------------------------------------------

namespace HubieTest.Dal
{
    using System;

    public partial class ATTACHMENT
    {
        public long ATTACHMENT_ID { get; set; }
        public long TICKET_ID { get; set; }
        public Nullable<long> INTERACTION_ID { get; set; }
        public string ATTACHMENT_NAME { get; set; }
        public string ATTACHMENT_TYPE { get; set; }
        public Nullable<long> ATTACHMENT_SIZE { get; set; }
        public string ATTACHMENT_PATH { get; set; }
        public long USER_ID { get; set; }
        public System.DateTime ATTACHMENT_CREATED_DT { get; set; }
    }
}
