//------------------------------------------------------------------------------
// <auto-generated>
//     Generated from the EDMX model (Database-First / EF6).
// </auto-generated>
//------------------------------------------------------------------------------

namespace HubieTest.Dal
{
    public partial class CATEGORY
    {
        public long CATEGORY_ID { get; set; }
        public string CATEGORY_NAME { get; set; }
        public bool CATEGORY_ACTIVE { get; set; }
    }
}
