//------------------------------------------------------------------------------
// <auto-generated>
//     DbContext generated from the EDMX model (Database-First / EF6).
//     Connection: "HubieContext" (see Web.config / App.config).
// </auto-generated>
//------------------------------------------------------------------------------

namespace HubieTest.Dal
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class HubieContext : DbContext
    {
        public HubieContext()
            : base("name=HubieContext")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<APP_USER> APP_USERS { get; set; }
        public virtual DbSet<CATEGORY> CATEGORIES { get; set; }
        public virtual DbSet<TICKET> TICKETS { get; set; }
        public virtual DbSet<INTERACTION> INTERACTIONS { get; set; }
        public virtual DbSet<ATTACHMENT> ATTACHMENTS { get; set; }
    }
}
