//------------------------------------------------------------------------------
// <auto-generated>
//     Generated from the EDMX model (Database-First / EF6).
// </auto-generated>
//------------------------------------------------------------------------------

namespace HubieTest.Dal
{
    using System;

    public partial class INTERACTION
    {
        public long INTERACTION_ID { get; set; }
        public long TICKET_ID { get; set; }
        public long USER_ID { get; set; }
        public string USER_NAME { get; set; }
        public string USER_PROFILE { get; set; }
        public string INTERACTION_MESSAGE { get; set; }
        public System.DateTime INTERACTION_CREATED_DT { get; set; }
    }
}
