//------------------------------------------------------------------------------
// <auto-generated>
//     Generated from the EDMX model (Database-First / EF6).
// </auto-generated>
//------------------------------------------------------------------------------

namespace HubieTest.Dal
{
    using System;

    public partial class TICKET
    {
        public long TICKET_ID { get; set; }
        public string TICKET_TITLE { get; set; }
        public string TICKET_DESCRIPTION { get; set; }
        public string TICKET_STATUS { get; set; }
        public long CATEGORY_ID { get; set; }
        public string CATEGORY_NAME { get; set; }
        public long REQUESTER_ID { get; set; }
        public string REQUESTER_NAME { get; set; }
        public Nullable<long> AGENT_ID { get; set; }
        public string AGENT_NAME { get; set; }
        public System.DateTime TICKET_CREATED_DT { get; set; }
        public Nullable<System.DateTime> TICKET_UPDATED_DT { get; set; }
        public Nullable<System.DateTime> TICKET_CLOSED_DT { get; set; }
    }
}
